**Numpy**

1. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

3.Create a 8x8 matrix and fill it with a checkerboard pattern

4.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

5.Normalize a 5x5 random matrix

6.Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [3]:
import numpy as np 
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==0.1*3)
print(0.1*3)

nan
False
False
nan
True
False
0.30000000000000004


In [6]:
import numpy as np 
array_range=1+np.arange(4)
modified_matrix=np.diag(array_range,k=-1)
print(modified_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [22]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [24]:
print(np.random.rand(5,5))

[[0.6767726  0.22193929 0.83460605 0.06599533 0.63356922]
 [0.5243856  0.66735571 0.88103941 0.63625786 0.35374614]
 [0.13909666 0.69312332 0.77594713 0.88038531 0.20950882]
 [0.50889461 0.03578991 0.45286123 0.85237329 0.92452728]
 [0.01635098 0.19720118 0.01634427 0.62178173 0.03208069]]


**Pandas**

1-Create a DataFrame: Create a DataFrame named df with columns 'Name', 'Age', and 'City' containing three rows of data.

2-Accessing Data: Print the first 5 rows of the DataFrame df.

3-Adding a Column: Add a new column 'Grade' to the DataFrame df with values ['A', 'B', 'C'].

4-Filtering Data: Create a new DataFrame young_df containing rows where 'Age' is less than 30.

5-Sorting Data: Sort the DataFrame df by 'Age' in ascending order.

6-Grouping and Aggregating: Group the DataFrame df by 'City' and calculate the average age in each city.

7-Merging DataFrames: Create two DataFrames df1 and df2 with columns 'ID' and 'Salary'. Merge them on 'ID' column.

8-Handling Missing Data: Create a DataFrame missing_df with missing values in some rows. Fill the missing values with the mean of the respective column.

9-Applying Functions: Create a new column 'Seniority' in the DataFrame df based on the 'Age' column. If 'Age' is greater than 40, label as 'Senior', else 'Junior'.

10-Plotting Data: Plot a bar chart showing the count of people in each 'Grade' category in the DataFrame df.

In [2]:
import pandas as pd 
data={'Name':['hazem','hamdy','hafez'],'Age':[21,25,26],'City':['Alex','Cairo','Berlin']}
df=pd.DataFrame(data)
print(df)

    Name  Age    City
0  hazem   21    Alex
1  hamdy   25   Cairo
2  hafez   26  Berlin


In [8]:
import pandas as pd 
import numpy as np 
x=np.random.rand(10,4)
df=pd.DataFrame(x)
print(df.head(5)) 

          0         1         2         3
0  0.875384  0.652018  0.962697  0.250285
1  0.381779  0.035916  0.514850  0.121505
2  0.293565  0.729854  0.269483  0.981357
3  0.974455  0.559156  0.310095  0.359921
4  0.966298  0.296104  0.752317  0.146766


In [9]:
import pandas as pd
data={'subject':['Math','English','hafez'],'Teacher':['Hazem','Hamdy','Hafez']}
df=pd.DataFrame(data)
df['Grade']=['A','B','C']
print(df)

subject Teacher Grade
0     Math   Hazem     A
1  English   Hamdy     B
2    hafez   Hafez     C

In [50]:
import pandas as pd 
data={'Name':['hazem','hamdy','hafez'],'Age':[21,50,30],'City':['Alex','Cairo','Berlin']}
df=pd.DataFrame(data)
print(df)
print('#'*50)
new_df=df.loc[df['Age']<30] #age less than 30 
print(new_df) 
print('#'*50)
new_df2=df.sort_values('Age',ascending=True) # ascending order 
print(new_df2)
print('#'*50)
new_df3=df.groupby('City')['Age'].agg('mean') # avg for ages in city
print(new_df3)
print('#'*50)
data1 = {'ID': [1, 2, 3, 4],'Salary': [50000, 60000, 70000, 80000]}
df1 = pd.DataFrame(data1)
data2 = {'ID': [1, 2, 3, 5],'Salary': [45000, 55000, 65000, 75000]}
df2 = pd.DataFrame(data2)
new_df4=pd.merge(df1,df2,on='ID')
print(new_df4)
print('#'*50)
data = {'A': [1, 2, np.nan, 4],
        'B': [5, np.nan, 7, 8],
        'C': [np.nan, 10, 11, 12]}
new_df5 = pd.DataFrame(data)
new_df5.fillna(new_df5.mean(), inplace=True)
print(new_df5)
print('#'*50)
data = {'Name': ['Hazem', 'Hamdy', 'Hafez', 'Ahmed'],'Age': [35, 45, 30, 50]}
new_df6 = pd.DataFrame(data)
new_df6['seniority']='Senior'
new_df6.loc[new_df6['Age'] < 40, 'seniority'] = 'junior'
print(new_df6)




    Name  Age    City
0  hazem   21    Alex
1  hamdy   50   Cairo
2  hafez   30  Berlin
##################################################
    Name  Age  City
0  hazem   21  Alex
##################################################
    Name  Age    City
0  hazem   21    Alex
2  hafez   30  Berlin
1  hamdy   50   Cairo
##################################################
City
Alex      21.0
Berlin    30.0
Cairo     50.0
Name: Age, dtype: float64
##################################################
   ID  Salary_x  Salary_y
0   1     50000     45000
1   2     60000     55000
2   3     70000     65000
##################################################
          A         B     C
0  1.000000  5.000000  11.0
1  2.000000  6.666667  10.0
2  2.333333  7.000000  11.0
3  4.000000  8.000000  12.0
##################################################


Name  Age seniority
0    Alice   35    junior
1      Bob   45    Senior
2  Charlie   30    junior
3    David   50    Senior